trigger: 
- main

pr:
- main

pool:
  name : CeenOtst

steps:
- script: echo Hello, world!!!!$$9999++++;;;
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI)
  displayName: 'Run a multi-line script'
  
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      FORKURI=$(curl -X GET "https://api.github.com/repos/$BUILD_REPOSITORY_NAME/pulls/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" | jq -r '.head.repo.clone_url')
          git clone "$FORKURI" .
          git checkout "$SYSTEM_PULLREQUEST_SOURCEBRANCH"

