trigger: 
- main

pr:
- main

pool:
  name : CeenOtst

steps:
- script: echo Hello, world!!!!$$9999++++;;;
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI)
  displayName: 'Run a multi-line script'
